### ISSUE TITLE
Are there plans to share the training and evaluation scripts?

### ISSUE THREAD

**Issue by bartmch** [abcxyzi/RadChar#3]
Hi, I could not find any Github repo reference to the experiments you did in the article. Do you plan to share these scripts, findings, weights, ... in the future Great work! Thank you.

**Comment by abcxyzi** [comment]
Hi @bartmch, thanks again for your interest! Unfortunately, we can't release our scripts due to commercial sensitivity at this time. However, we are actively exploring related work in this domain, with new publications on the horizon.
